<?php
/**
 * Majori Manor — every constant the application reads, with placeholder values.
 *
 * Copy to private/config.php and fill in. config.php is NOT committed
 * (see .gitignore); this file is.
 *
 *     cp private/config.example.php private/config.php
 *
 * NO REAL SECRET BELONGS IN THIS FILE. It is committed, so every value here is
 * either a placeholder or a safe default. The two that must be replaced before
 * the site can send mail are SMTP_PASS and FORM_SECRET.
 *
 * The list is exhaustive as of this deploy: it was generated by tokenising
 * public_html/ and collecting every constant referenced but not defined in
 * application code. If a new constant is added to the app, add it here too.
 */

declare(strict_types=1);

// ---------------------------------------------------------------------------
// Languages
// ---------------------------------------------------------------------------

/** Active languages; adding 'lv' activates Latvian under /lv/. */
define('LANGS', ['en']);

/** Served at the root, with no /<lang>/ prefix. */
define('DEFAULT_LANG', 'en');

// ---------------------------------------------------------------------------
// Site
// ---------------------------------------------------------------------------

/** Absolute base URL, no trailing slash — every canonical, JSON-LD url and sitemap entry derives from this. */
define('SITE_URL', 'https://majorimanor.com');

/** true shows PHP errors and marks missing translation keys; false is the production value. */
define('DEV', false);

// ---------------------------------------------------------------------------
// Mail
// ---------------------------------------------------------------------------

/** SMTP server hostname. */
define('SMTP_HOST', '');

/** SMTP port — 465 for implicit TLS, 587 for STARTTLS. */
define('SMTP_PORT', 465);

/** Transport security: 'ssl' for port 465, 'tls' for 587, '' for none. */
define('SMTP_SECURE', 'ssl');

/** SMTP account the site authenticates as. */
define('SMTP_USER', '');

/** SMTP account password — SET THIS PER ENVIRONMENT AND NEVER COMMIT IT. */
define('SMTP_PASS', '');

/** Envelope From address on outgoing mail. */
define('SMTP_FROM', '');

/** Display name on outgoing mail. */
define('SMTP_FROM_NAME', 'Majori Manor');

/** Where enquiries and membership applications are delivered. */
define('MAIL_TO', '');

// ---------------------------------------------------------------------------
// Forms
// ---------------------------------------------------------------------------

/**
 * Signs the forms' time-trap and salts the rate limiter's address hashes.
 * GENERATE A REAL ONE PER ENVIRONMENT AND NEVER COMMIT IT:
 *
 *     php -r "echo bin2hex(random_bytes(32)), PHP_EOL;"
 */
define('FORM_SECRET', '');

/** Submissions ACCEPTED per address per hour — the ceiling that protects the inbox. */
define('FORM_RATE_LIMIT', 5);

/** POSTs of any kind per address per hour, accepted or not — protects the server. */
define('FORM_RATE_LIMIT_POSTS', 20);

// ---------------------------------------------------------------------------
// Map
// ---------------------------------------------------------------------------

/**
 * CARTO basemap key. Leave this commented out and the tiles come back
 * watermarked "API KEY REQUIRED" — CARTO changed the terms of their keyless
 * raster basemaps. Everything else about the map on /contact works either way:
 * the address, the coordinates, the pin, the pan and the zoom.
 *
 * Get one from a CARTO account and uncomment. Nothing else has to change.
 */
// define('MAP_API_KEY', '');

// ---------------------------------------------------------------------------
// Social
// ---------------------------------------------------------------------------

/** Footer social profiles: [['label' => 'Instagram', 'url' => '…']]. Empty renders nothing. */
define('SOCIAL', []);

// ---------------------------------------------------------------------------
// Feature flags
// ---------------------------------------------------------------------------

/** Hero background video; the markup in templates/components/hero.php is inert while this is false. */
define('ENABLE_VIDEO', false);

/** The private gaming section of /after-dark — false is the production value; publishing it is the owner's decision. */
define('ENABLE_GAMING', false);
